baseURL = "https://syphon5.com"
languageCode = "en-us"
title = "Data Shenanigans with Steven Wroblewski | Syphon5"
theme = "hugo-frais"

[params]
	indexHeadline = "Data Shenanigans"
    author = "Steven Wroblewski"
    pseudo = "syphon5"
    twitter = "stevonio"
    linkedin = "steven-wroblewski"
    headline = "Syphon5"
    description = "Data analysis projects by Steven Wroblewski. Go on and read about my random analysis and other fine goods."
    mainSections = ["blog", "post"]
    logo = "/img/meow.png"

[taxonomies]
    category = "categories"
    tag = "tags"

[[menu.main]]
    name = "Posts"
    pre = ""
    url = "/post/"
    identifier = "post"
    weight = 1
[[menu.main]]
    name = "About"
    pre = ""
    url = "/about/"
    identifier = "about"
    weight = 2